# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Project_FPGA/Nexys4DDR_Master.xdc

# Block Designs: bd/DCC/DCC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC || ORIG_REF_NAME==DCC} -quiet] -quiet

# IP: bd/DCC/ip/DCC_microblaze_0_0/DCC_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_microblaze_0_0 || ORIG_REF_NAME==DCC_microblaze_0_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_dlmb_v10_0/DCC_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_dlmb_v10_0 || ORIG_REF_NAME==DCC_dlmb_v10_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_ilmb_v10_0/DCC_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_ilmb_v10_0 || ORIG_REF_NAME==DCC_ilmb_v10_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_dlmb_bram_if_cntlr_0/DCC_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DCC_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_ilmb_bram_if_cntlr_0/DCC_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DCC_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_lmb_bram_0/DCC_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_lmb_bram_0 || ORIG_REF_NAME==DCC_lmb_bram_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_xbar_0/DCC_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_xbar_0 || ORIG_REF_NAME==DCC_xbar_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_microblaze_0_axi_periph_0/DCC_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DCC_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_microblaze_0_axi_intc_0/DCC_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DCC_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_microblaze_0_xlconcat_0/DCC_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_microblaze_0_xlconcat_0 || ORIG_REF_NAME==DCC_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_mdm_1_0/DCC_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_mdm_1_0 || ORIG_REF_NAME==DCC_mdm_1_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_clk_wiz_1_0/DCC_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_clk_wiz_1_0 || ORIG_REF_NAME==DCC_clk_wiz_1_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_rst_clk_wiz_1_100M_0/DCC_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DCC_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_axi_gpio_0_0/DCC_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_axi_gpio_0_0 || ORIG_REF_NAME==DCC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_axi_gpio_0_1 || ORIG_REF_NAME==DCC_axi_gpio_0_1} -quiet] -quiet

# IP: bd/DCC/ip/DCC_SS_0_0/DCC_SS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_SS_0_0 || ORIG_REF_NAME==DCC_SS_0_0} -quiet] -quiet

# IP: bd/DCC/ip/DCC_DCC_0_0/DCC_DCC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCC_DCC_0_0 || ORIG_REF_NAME==DCC_DCC_0_0} -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/DCC_ooc.xdc
