# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.srcs/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1.xci
# IP: The module: 'DCC_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.srcs/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1.xci
# IP: The module: 'DCC_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA/Project_FPGA.gen/sources_1/bd/DCC/ip/DCC_axi_gpio_0_1/DCC_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCC_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
