# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# Block Designs: bd/TP3/TP3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3 || ORIG_REF_NAME==TP3} -quiet] -quiet

# IP: bd/TP3/ip/TP3_microblaze_0_0/TP3_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_microblaze_0_0 || ORIG_REF_NAME==TP3_microblaze_0_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_dlmb_v10_0/TP3_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_dlmb_v10_0 || ORIG_REF_NAME==TP3_dlmb_v10_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_ilmb_v10_0/TP3_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_ilmb_v10_0 || ORIG_REF_NAME==TP3_ilmb_v10_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_dlmb_bram_if_cntlr_0/TP3_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP3_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_ilmb_bram_if_cntlr_0/TP3_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP3_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_lmb_bram_0/TP3_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_lmb_bram_0 || ORIG_REF_NAME==TP3_lmb_bram_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_xbar_0/TP3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_xbar_0 || ORIG_REF_NAME==TP3_xbar_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_microblaze_0_axi_periph_0/TP3_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TP3_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_microblaze_0_axi_intc_0/TP3_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TP3_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_mdm_1_0/TP3_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_mdm_1_0 || ORIG_REF_NAME==TP3_mdm_1_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_clk_wiz_1_0 || ORIG_REF_NAME==TP3_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_rst_clk_wiz_1_100M_0/TP3_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TP3_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_boutons_0/TP3_boutons_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_boutons_0 || ORIG_REF_NAME==TP3_boutons_0} -quiet] -quiet

# IP: bd/TP3/ip/TP3_my_led_0_0/TP3_my_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP3_my_led_0_0 || ORIG_REF_NAME==TP3_my_led_0_0} -quiet] -quiet

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/TP3_ooc.xdc
