# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Project_FPGA/Nexys4DDR_Master.xdc

# Block Designs: bd/Project_FPGA/Project_FPGA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA || ORIG_REF_NAME==Project_FPGA} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_microblaze_0_0/Project_FPGA_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_dlmb_v10_0/Project_FPGA_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_dlmb_v10_0 || ORIG_REF_NAME==Project_FPGA_dlmb_v10_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_ilmb_v10_0/Project_FPGA_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_ilmb_v10_0 || ORIG_REF_NAME==Project_FPGA_ilmb_v10_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_dlmb_bram_if_cntlr_0/Project_FPGA_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Project_FPGA_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_ilmb_bram_if_cntlr_0/Project_FPGA_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Project_FPGA_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_lmb_bram_0/Project_FPGA_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_lmb_bram_0 || ORIG_REF_NAME==Project_FPGA_lmb_bram_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_xbar_0/Project_FPGA_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_xbar_0 || ORIG_REF_NAME==Project_FPGA_xbar_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_microblaze_0_axi_periph_0/Project_FPGA_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_microblaze_0_axi_intc_0/Project_FPGA_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_mdm_1_0/Project_FPGA_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_mdm_1_0 || ORIG_REF_NAME==Project_FPGA_mdm_1_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_clk_wiz_1_0/Project_FPGA_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_clk_wiz_1_0 || ORIG_REF_NAME==Project_FPGA_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_rst_clk_wiz_1_100M_0/Project_FPGA_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_axi_gpio_0_0/Project_FPGA_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_0_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_axi_gpio_1_0/Project_FPGA_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_1_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Project_FPGA/ip/Project_FPGA_IP_Centrale_DCC_0_0/Project_FPGA_IP_Centrale_DCC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Project_FPGA_IP_Centrale_DCC_0_0 || ORIG_REF_NAME==Project_FPGA_IP_Centrale_DCC_0_0} -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_microblaze_0_0/Project_FPGA_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_microblaze_0_0/Project_FPGA_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_lmb_bram_0/Project_FPGA_lmb_bram_0_ooc.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_microblaze_0_axi_intc_0/Project_FPGA_microblaze_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_microblaze_0_axi_intc_0/Project_FPGA_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Project_FPGA_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_microblaze_0_axi_intc_0/Project_FPGA_microblaze_0_axi_intc_0_ooc.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_mdm_1_0/Project_FPGA_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_mdm_1_0 || ORIG_REF_NAME==Project_FPGA_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_mdm_1_0/Project_FPGA_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_clk_wiz_1_0/Project_FPGA_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_clk_wiz_1_0 || ORIG_REF_NAME==Project_FPGA_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_clk_wiz_1_0/Project_FPGA_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_clk_wiz_1_0 || ORIG_REF_NAME==Project_FPGA_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_clk_wiz_1_0/Project_FPGA_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_rst_clk_wiz_1_100M_0/Project_FPGA_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_rst_clk_wiz_1_100M_0/Project_FPGA_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Project_FPGA_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_0_0/Project_FPGA_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_0_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_0_0/Project_FPGA_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_0_0/Project_FPGA_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_0_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_1_0/Project_FPGA_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_1_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_1_0/Project_FPGA_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/ip/Project_FPGA_axi_gpio_1_0/Project_FPGA_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Project_FPGA_axi_gpio_1_0 || ORIG_REF_NAME==Project_FPGA_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marcs/OneDrive/Bureau/Desktop/FPGA/Project_FPGA_IP/Project_FPGA_IP.gen/sources_1/bd/Project_FPGA/Project_FPGA_ooc.xdc
