# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.srcs/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0.xci
# IP: The module: 'TP3_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.srcs/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0.xci
# IP: The module: 'TP3_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/UserTP/Desktop/FPGA-main/TP3/TP3.gen/sources_1/bd/TP3/ip/TP3_clk_wiz_1_0/TP3_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP3_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
