# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# Block Designs: bd/TP2/TP2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2 || ORIG_REF_NAME==TP2} -quiet] -quiet

# IP: bd/TP2/ip/TP2_microblaze_0_0/TP2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_0 || ORIG_REF_NAME==TP2_microblaze_0_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_dlmb_v10_0/TP2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_dlmb_v10_0 || ORIG_REF_NAME==TP2_dlmb_v10_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_ilmb_v10_0 || ORIG_REF_NAME==TP2_ilmb_v10_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_dlmb_bram_if_cntlr_0/TP2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_ilmb_bram_if_cntlr_0/TP2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_lmb_bram_0 || ORIG_REF_NAME==TP2_lmb_bram_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_xbar_0/TP2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_xbar_0 || ORIG_REF_NAME==TP2_xbar_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_microblaze_0_axi_periph_0/TP2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_microblaze_0_axi_intc_0/TP2_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_microblaze_0_xlconcat_0/TP2_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TP2_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_mdm_1_0/TP2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_mdm_1_0 || ORIG_REF_NAME==TP2_mdm_1_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_clk_wiz_1_0/TP2_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_clk_wiz_1_0 || ORIG_REF_NAME==TP2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_rst_clk_wiz_1_100M_0/TP2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TP2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_axi_gpio_0_0/TP2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_0 || ORIG_REF_NAME==TP2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TP2/ip/TP2_axi_gpio_0_1/TP2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_1 || ORIG_REF_NAME==TP2_axi_gpio_0_1} -quiet] -quiet

# XDC: c:/Users/28607510/Desktop/TP2_M1S2_FPGA/TP2_M1S2_FPGA.gen/sources_1/bd/TP2/TP2_ooc.xdc
