# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/28607510/Desktop/TP2_M1S2_FPGA/TP2_M1S2_FPGA.srcs/sources_1/bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0.xci
# IP: The module: 'TP2_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/28607510/Desktop/TP2_M1S2_FPGA/TP2_M1S2_FPGA.gen/sources_1/bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP2_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/28607510/Desktop/TP2_M1S2_FPGA/TP2_M1S2_FPGA.srcs/sources_1/bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0.xci
# IP: The module: 'TP2_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/28607510/Desktop/TP2_M1S2_FPGA/TP2_M1S2_FPGA.gen/sources_1/bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP2_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
