@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri May 19 16:39:58 +0200 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 1e5d8116712748de85efcacbae10ef8a --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TOP_tb_func_synth xil_defaultlib.TOP_tb -log elaborate.log"
call xelab  -wto 1e5d8116712748de85efcacbae10ef8a --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TOP_tb_func_synth xil_defaultlib.TOP_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
